{% set name = "libonvif" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - libxml2=2.10.2 # [win]
    - libxml2 # [linux]
    - qt
  run:
    - libxml2=2.10.2 # [win]
    - libxml2 # [linux]
    - qt

test:
  commands:
    - echo test

about:
  summary: client side implementation of ONVIF
